// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package fr.epf.lastminutetraining.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransactionBuilder extends
		TransactionBuilderBase<TransactionBuilder> {
	public static TransactionBuilder transaction() {
		return new TransactionBuilder();
	}

	public TransactionBuilder() {
		super(new Transaction());
	}

	public Transaction build() {
		return getInstance();
	}
}

class TransactionBuilderBase<GeneratorT extends TransactionBuilderBase<GeneratorT>> {
	private Transaction instance;

	protected TransactionBuilderBase(Transaction aInstance) {
		instance = aInstance;
	}

	protected Transaction getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT client(Client aValue) {
		instance.setClient(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT date(Date aValue) {
		instance.setDate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT status(String aValue) {
		instance.setStatus(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT orders(List<Order> aValue) {
		instance.setOrders(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT addOrder(Order aValue) {
		if (instance.getOrders() == null) {
			instance.setOrders(new ArrayList<Order>());
		}

		((ArrayList<Order>) instance.getOrders()).add(aValue);

		return (GeneratorT) this;
	}
}
